---
pipeline:
  test:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install -r requirements/ci.txt
      - bash tcp-port-wait.sh postgres 5432
      - python manage.py makemigrations --check --dry-run
    when:
      event: [pull_request, push, tag]
    environment:
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "db"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"

  bandit:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install bandit
      - bandit -x tests/ -r -lll .
    when:
      event: [pull_request, push, tag]

  build-docker-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec/products_service
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]

services:
  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

matrix:
  PYTHON_VERSION:
    - 3.7
  POSTGRESQL_VERSION:
    - 10.4
